### ISSUE TITLE
TCC deny IOHIDDeviceOpen for pam_yubico in macOS 10.15 Beta 3

### ISSUE THREAD

**Issue by tsujamin** [Yubico/yubico-pam#197]
Since updating to the macOS 10.15 public beta, I'm unable to use pam_yubico with sudo. I did a bit of research and it might be due to the built in sudo executable missing the "com.apple.security.device.usb" sandbox entitlement, preventing pam_yubico from interacting with my key. I can't see a specific sandbox change in the release notes that would cause this.

I don't know if there's someway for pam_yubico to request this entitlement during authentication? I imagine it might affect other sandboxed PAM  applications and users on macOS 10.15.

My debug output is:
```
[I] benjamin ) sudo xcode-select -s /Applications/Xcode-beta.app
Password:
debug: pam_yubico.c:838 (parse_cfg): called.
debug: pam_yubico.c:839 (parse_cfg): flags -2147483648 argc 3
debug: pam_yubico.c:841 (parse_cfg): argv[0]=mode=challenge-response
debug: pam_yubico.c:841 (parse_cfg): argv[1]=alwaysok
debug: pam_yubico.c:841 (parse_cfg): argv[2]=debug
debug: pam_yubico.c:842 (parse_cfg): id=0
debug: pam_yubico.c:843 (parse_cfg): key=(null)
debug: pam_yubico.c:844 (parse_cfg): debug=1
debug: pam_yubico.c:845 (parse_cfg): debug_file=1
debug: pam_yubico.c:846 (parse_cfg): alwaysok=1
debug: pam_yubico.c:847 (parse_cfg): verbose_otp=0
debug: pam_yubico.c:848 (parse_cfg): try_first_pass=0
debug: pam_yubico.c:849 (parse_cfg): use_first_pass=0
debug: pam_yubico.c:850 (parse_cfg): nullok=0
debug: pam_yubico.c:851 (parse_cfg): authfile=(null)
debug: pam_yubico.c:852 (parse_cfg): ldapserver=(null)
debug: pam_yubico.c:853 (parse_cfg): ldap_uri=(null)
debug: pam_yubico.c:854 (parse_cfg): ldap_bind_user=(null)
debug: pam_yubico.c:855 (parse_cfg): ldap_bind_password=(null)
debug: pam_yubico.c:856 (parse_cfg): ldap_filter=(null)
debug: pam_yubico.c:857 (parse_cfg): ldap_cacertfile=(null)
debug: pam_yubico.c:858 (parse_cfg): ldapdn=(null)
debug: pam_yubico.c:859 (parse_cfg): user_attr=(null)
debug: pam_yubico.c:860 (parse_cfg): yubi_attr=(null)
debug: pam_yubico.c:861 (parse_cfg): yubi_attr_prefix=(null)
debug: pam_yubico.c:862 (parse_cfg): url=(null)
debug: pam_yubico.c:863 (parse_cfg): urllist=(null)
debug: pam_yubico.c:864 (parse_cfg): capath=(null)
debug: pam_yubico.c:865 (parse_cfg): cainfo=(null)
debug: pam_yubico.c:866 (parse_cfg): proxy=(null)
debug: pam_yubico.c:867 (parse_cfg): token_id_length=12
debug: pam_yubico.c:868 (parse_cfg): mode=chresp
debug: pam_yubico.c:869 (parse_cfg): chalresp_path=(null)
debug: pam_yubico.c:899 (pam_sm_authenticate): pam_yubico version: 2.26
debug: pam_yubico.c:914 (pam_sm_authenticate): get user returned: benjamin
debug: pam_yubico.c:490 (do_challenge_response): Checking for user challenge files
debug: pam_yubico.c:493 (do_challenge_response): Challenge files found
debug: pam_yubico.c:514 (do_challenge_response): Failed initializing YubiKey
debug: pam_yubico.c:706 (do_challenge_response): USB error: unknown error
debug: pam_yubico.c:718 (do_challenge_response): Challenge response failed: No such file or directory
debug: pam_yubico.c:1217 (pam_sm_authenticate): alwaysok needed (otherwise return with 9)
debug: pam_yubico.c:1220 (pam_sm_authenticate): done. [success]
```

Looking at console/syslog:
```
error	21:33:12.895898+1000	sudo	TCC deny IOHIDDeviceOpen
```

This is the entitlements of the default sudo binary
```
?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.private.AuthorizationServices</key>
	<array>
		<string>com.apple.security.sudo</string>
	</array>
</dict>
</plist>
```

**Comment by tsujamin** [comment]
Looks like the sandboxing got fixed in the latest public beta, so not a pam_yubico bug. Sorry!

**Comment by tob1k** [comment]
@tsujamin When you closed this issue, had you resolved the problem?

It seems like this issue still exists in the Catalina GM

**Comment by tsujamin** [comment]
Background: I had pam_yubico in /etc/pam.d/{authorization,logon,su,sudo,screensaver}. It started working again in either a later macOS beta or after an iTerm update (can't remember) caused a new sandbox permission prompt to appear (allowing USB access iirc).

A later beta overwrote my PAM configs so hadn't tested it in a while until now. At the moment (on GM) I can use sudo/su with pam_yubico enabled from iTerm successfully, but if I enable authorization/screensaver I'm no longer able to login/unlock.
